---
permalink: /25/8/17/scala/scala-exception
---


# Scala异常体系

## 1 **简介**

Scala异常语法处理上和Java类似，但是又不尽相同。

Java异常：

Java中对于异常的处理一般有两种方式：

-   捕获`try-catch-finally`：常用于需要释放资源的场景
    -   在java7后实现了`Closeable`/`AutoCloseable`的类可以使用`try-with-resource`（语法糖）方式释放资源
-   抛出`throw`

演示：

```java
try {
    int a = 10;
    int b = 0;
    int c = a / b;
} catch (ArithmeticException e){
    // catch时，需要将范围小的写到前面
    e.printStackTrace();
} catch (Exception e){
    e.printStackTrace();
} finally {
    System.out.println("finally");
}
```



## 2 基本语法

```scala
object ScalaException {
    def main(args: Array[String]): Unit = {
        try {
            var n= 10 / 0
        } catch {
            case ex: ArithmeticException=>{
                // 发生算术异常
                println("发生算术异常")
            }
            case ex: Exception=>{
                // 对异常处理
                println("发生了异常1")
            }
        } finally {
            println("finally")
        }
    }
}
```
::: tip 说明
- **Scala中的异常不区分所谓的编译时异常和运行时异常，也无需显示抛出方法异常，所以Scala中没有`throws`关键字。**
- 因为Scala 没有“checked(编译期)”异常，即 Scala 没有编译异常这个概念，异常都是在运行的时候捕获处理 
- 如果Java程序调用scala代码，需要增加注解 `@throws(Exception)`明确异常
:::
